name: Build, Test and Sonar

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      # Wait until MySQL container is healthy
      - name: Wait for MySQL to be healthy
        run: |
          # Get container id for mysql service
          container_id=$(docker ps --filter "ancestor=mysql:8" --format="{{.ID}}")
          # Wait until the container’s health status is "healthy"
          while [ "$(docker inspect --format='{{.State.Health.Status}}' $container_id)" != "healthy" ]; do
            echo "Waiting for MySQL container to be healthy..."
            sleep 2
          done
          echo "MySQL is healthy!"

      - name: Verify MySQL container status
        run: docker ps --filter "ancestor=mysql:8"

      - name: Build and run tests with coverage
        run: mvn clean verify

      - name: Generate JaCoCo XML Report
        run: mvn jacoco:report

      - name: SonarCloud Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # For PR info
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
          -Dsonar.projectKey=eXp3r7a_web-crawler-git-actions-sonar-jacoco
